### ISSUE TITLE
Datepicker inside bootstrap modal appears behind the modal. 

### ISSUE THREAD

**Issue by roemhildtg** [skinnybrit51/date-selector#8]
![image](https://cloud.githubusercontent.com/assets/5471079/15548280/4a371678-226d-11e6-929a-0c3123f5463d.png)

Is there a css override or any other suggestions?

**Comment by roemhildtg** [comment]
Easy fix actually. Modals have a z-index of 1040, so adding a date-selector z-index of 1050 solves the problem.

**Comment by ghost** [comment]
https://github.com/skinnybrit51/date-selector/commit/54bb9cb044a8e90c80d629ab22741bc6758c3e80
